### PR TITLE
add flake and Cargo.lock required by naersk

### PR DESCRIPTION
**Pull request by Artturin**
I want to be able to run this program with nix run

`cargo upgrade` is from `cargo-edit`

### CODE REVIEW

**Review by trofi — APPROVED** [review]

**Comment by trofi** [comment]
Looks great! Thank you!

**Comment by trofi** [comment]
Silly question: is `nix shell` expected to pull in all depends for `cargo` to just work? Or it could use only build helpers from `nixpkgs`?

Looks like `cc` is missing if I try the simplest `cargo build`:

```
$ nix shell -i
bash-5.2$ cargo build
   Compiling proc-macro2 v1.0.64
   Compiling unicode-ident v1.0.11
   Compiling quote v1.0.29
   Compiling rustix v0.38.4
   Compiling linux-raw-sys v0.4.3
   Compiling bitflags v2.3.3
   Compiling utf8parse v0.2.1
   Compiling libc v0.2.147
   Compiling colorchoice v1.0.0
   Compiling serde v1.0.171
   Compiling anstyle-query v1.0.0
   Compiling anstyle v1.0.1
   Compiling serde_json v1.0.102
   Compiling thiserror v1.0.43
   Compiling strsim v0.10.0
   Compiling heck v0.4.1
   Compiling anstyle-parse v0.2.1
   Compiling clap_lex v0.5.0
   Compiling itoa v1.0.8
   Compiling once_cell v1.18.0
error: linker `cc` not found
  |
  = note: No such file or directory (os error 2)
```

**Comment by Artturin** [comment]
`nix shell` only contains the program

you need to use `nix develop` for the development setup

**Comment by trofi** [comment]
Aha, completely confused both. Thank you!

My `cargo` came from `environment.systemPackages`. Dropped from there.

**Pull request merged**
